# Generated by Django 5.2.17 on 2026-09-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_roomtype_default_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staah_property_id', models.CharField(db_index=True, max_length=100)),
                ('staah_room_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('staah_rate_plan_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_mappings', to='properties.property')),
                ('rate_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_mappings', to='properties.rateplan')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_mappings', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Channel Mapping',
                'verbose_name_plural': 'Channel Mappings',
                'db_table': 'channel_mappings',
                'unique_together': {('property', 'room_type', 'rate_plan')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_type', models.CharField(choices=[('AVAILABILITY', 'Availability'), ('RATE', 'Rate'), ('RESTRICTION', 'Restriction'), ('RESERVATION_IN', 'Reservation (Incoming)'), ('MODIFICATION_IN', 'Modification (Incoming)'), ('CANCELLATION_IN', 'Cancellation (Incoming)')], max_length=30)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound (Push to STAAH)'), ('INBOUND', 'Inbound (From STAAH)')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='properties.property')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'sync_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'sync_type', 'status'], name='sync_logs_propert_bb65f2_idx'), models.Index(fields=['created_at'], name='sync_logs_created_07d9f3_idx')],
            },
        ),
    ]
