# Generated by Django 5.2.17 on 2026-09-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('properties', '0002_roomtype_default_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='channelmapping',
            name='channex_property_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='channelmapping',
            name='channex_rate_plan_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='channelmapping',
            name='channex_room_type_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='channelmapping',
            name='provider',
            field=models.CharField(choices=[('STAAH', 'STAAH'), ('CHANNEX', 'Channex')], default='CHANNEX', max_length=20),
        ),
        migrations.AlterField(
            model_name='channelmapping',
            name='staah_property_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='channelmapping',
            unique_together={('provider', 'property', 'room_type', 'rate_plan')},
        ),
    ]
