# Generated by Django 5.2.17 on 2026-09-18 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('check_in_time', models.TimeField(default='12:00:00')),
                ('check_out_time', models.TimeField(default='11:00:00')),
                ('tax_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('max_adults', models.PositiveSmallIntegerField(default=2)),
                ('max_children', models.PositiveSmallIntegerField(default=0)),
                ('max_occupancy', models.PositiveSmallIntegerField(default=2)),
                ('base_occupancy', models.PositiveSmallIntegerField(default=2)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='properties.property')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'db_table': 'room_types',
                'ordering': ['property', 'name'],
                'unique_together': {('property', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('meal_plan', models.CharField(blank=True, max_length=100)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('is_refundable', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='properties.property')),
            ],
            options={
                'verbose_name': 'Rate Plan',
                'verbose_name_plural': 'Rate Plans',
                'db_table': 'rate_plans',
                'ordering': ['property', 'name'],
                'unique_together': {('property', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('BLOCKED', 'Blocked'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['property', 'room_type', 'room_number'],
                'unique_together': {('property', 'room_number')},
            },
        ),
    ]
