# Generated by Django 5.2.17 on 2026-09-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed nightly price used when no date-specific RoomRate exists.', max_digits=10),
        ),
    ]
