# Generated by Django 5.2.17 on 2026-09-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adjustment_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Increase/Decrease'), ('FLAT', 'Flat Amount Increase/Decrease'), ('OVERRIDE', 'Fixed Price Override')], max_length=20)),
                ('adjustment_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='properties.property')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='properties.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Seasonal Rate',
                'verbose_name_plural': 'Seasonal Rates',
                'db_table': 'seasonal_rates',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='properties.property')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='properties.room')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availability',
                'db_table': 'availability',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['room', 'date'], name='availabilit_room_id_ef795e_idx'), models.Index(fields=['property', 'date', 'is_available'], name='availabilit_propert_a9d405_idx')],
                'unique_together': {('room', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('min_stay', models.PositiveSmallIntegerField(default=1)),
                ('max_stay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('closed_to_arrival', models.BooleanField(default=False)),
                ('closed_to_departure', models.BooleanField(default=False)),
                ('stop_sell', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='properties.property')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='properties.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Restriction',
                'verbose_name_plural': 'Restrictions',
                'db_table': 'restrictions',
                'ordering': ['date'],
                'unique_together': {('room_type', 'rate_plan', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_adult_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_child_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_rates', to='properties.property')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='properties.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Room Rate',
                'verbose_name_plural': 'Room Rates',
                'db_table': 'room_rates',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['room_type', 'rate_plan', 'date'], name='room_rates_room_ty_b58f73_idx')],
                'unique_together': {('room_type', 'rate_plan', 'date')},
            },
        ),
    ]
