# Generated by Django 5.2.17 on 2026-09-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_invoice_payment_refund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
